/*
 Generated by typeshare 1.13.3
*/

export interface TimeBlock {
  /** Day of week for the time block. */
  day?: string;
  /** Start time value for the block. */
  t1?: string;
  /** End time value for the block. */
  t2?: string;
}

export interface Block {
  /** Campus code or name for the block. */
  campus?: string;
  /** Display string for the block. */
  display?: string;
  /** Location string for the block. */
  location?: string;
  /** Time blocks associated with this block. */
  timeblocks?: TimeBlock[];
  /** Course reference number for the block. */
  crn?: string;
}

export interface ChangelogItem {
  number: number;
  summary?: string;
  url: string;
  mergedAt: string;
}

export interface Instructor {
  /** Instructor display name. */
  name: string;
  /** Search n-grams for the instructor name. */
  nameNgrams?: string;
  /** Term identifier for the instructor record. */
  term: string;
}

export type ReqNode =
  /** A single course code requirement. */
  | { type: 'course'; data: string }
  /** A group of requirement nodes combined by an operator. */
  | {
      type: 'group';
      data: {
        /** Operator used to combine the child nodes. */
        operator: Operator;
        /** Child requirement nodes in the group. */
        groups: ReqNode[];
      };
    };

export interface Schedule {
  /** Schedule blocks for the term. */
  blocks?: Block[];
  /** Term identifier for the schedule. */
  term?: string;
}

export interface Course {
  /** Unique course identifier. */
  _id: string;
  /** Search n-grams for the course ID. */
  idNgrams?: string;
  /** Course title. */
  title: string;
  /** Search n-grams for the course title. */
  titleNgrams?: string;
  /** Credit value as listed in the catalog. */
  credits: string;
  /** Subject code (e.g., "COMP"). */
  subject: string;
  /** Course number (e.g., "202"). */
  code: string;
  /** Catalog URL for the course. */
  url: string;
  /** Department offering the course. */
  department: string;
  /** Faculty offering the course. */
  faculty: string;
  /** Terms when the course is offered. */
  terms: string[];
  /** Course description. */
  description: string;
  /** Instructors associated with the course. */
  instructors: Instructor[];
  /** Raw prerequisites text from the catalog. */
  prerequisitesText?: string;
  /** Raw corequisites text from the catalog. */
  corequisitesText?: string;
  /** List of prerequisite course codes. */
  prerequisites: string[];
  /** List of corequisite course codes. */
  corequisites: string[];
  /** Course codes that list this course as a prerequisite. */
  leadingTo: string[];
  /** Structured prerequisites expression. */
  logicalPrerequisites?: ReqNode;
  /** Structured corequisites expression. */
  logicalCorequisites?: ReqNode;
  /** Restriction text from the catalog. */
  restrictions?: string;
  /** Schedule offerings for the course. */
  schedule?: Schedule[];
  /** Average rating across reviews. */
  avgRating: number;
  /** Average difficulty across reviews. */
  avgDifficulty: number;
  /** Number of reviews for the course. */
  reviewCount: number;
}

export interface CourseAverage {
  /** Course identifier (e.g., "COMP202"). */
  courseId: string;
  /** Term name (e.g., "Fall 2024", "Winter 2025"). */
  term: string;
  /** Letter grade average (e.g., "A-", "B+"). */
  average: string;
}

export enum CourseSortType {
  /** Sort by course difficulty. */
  Difficulty = 'difficulty',
  /** Sort by course rating. */
  Rating = 'rating',
  /** Sort by number of reviews. */
  ReviewCount = 'reviewCount',
}

export interface CourseFilter {
  /** Course levels to filter by (e.g., "1", "2", "3"). */
  levels?: string[];
  /** Search query string. */
  query?: string;
  /** Whether to reverse the sort order. */
  sortReverse?: boolean;
  /** Sort type for ordering results. */
  sortType?: CourseSortType;
  /** Subject codes to filter by (e.g., "COMP", "MATH"). */
  subjects?: string[];
  /** Term identifiers to filter by (e.g., "Fall 2024"). */
  terms?: string[];
}

export interface FinalExam {
  /** Course identifier (e.g., "COMP202"). */
  id: string;
  /** Section number (e.g., "001"). */
  section: string;
  /** Exam format (e.g., "IN-PERSON", "ONLINE"). */
  format: string;
  /** Exam type (e.g., "FORMAL EXAM"). */
  type: string;
  /** Location where the exam is held. */
  location?: string;
  /** Exam start time in ISO 8601 format. */
  startTime: string;
  /** Exam end time in ISO 8601 format. */
  endTime: string;
}

export interface FinalExamGroup {
  /** Term name (e.g., "Fall 2025", "Winter 2026"). */
  term: string;
  /** URL to the official exam schedule PDF. */
  url: string;
  /** List of final exams for this group. */
  exams: FinalExam[];
}

export interface GetCourseAveragesPayload {
  /** List of course grade averages by term. */
  courseAverages: CourseAverage[];
}

export interface Review {
  /** The text content of the review. */
  content: string;
  /** The course ID this review is for. */
  courseId: string;
  /** Difficulty rating from 1-5. */
  difficulty: number;
  /** List of instructor names for this review. */
  instructors: string[];
  /** Number of likes (net of dislikes) this review has received. */
  likes: number;
  /** Overall rating from 1-5. */
  rating: number;
  /** Timestamp when the review was created or last updated. */
  timestamp: string;
  /** The user ID of the review author. */
  userId: string;
}

export interface GetCourseByIdPayload {
  /** The course information. */
  course: Course;
  /** Grade averages for the course by term. */
  courseAverages: CourseAverage[];
  /** Reviews for the course (sorted by timestamp, newest first). */
  reviews: Review[];
}

export interface GetCoursesPayload {
  /** Total number of courses available (if requested). */
  courseCount?: number;
  /** List of courses matching the query. */
  courses: Course[];
}

export interface GetInstructorPayload {
  /** Instructor matching the requested name, if found. */
  instructor?: Instructor;
  /** Reviews associated with the instructor sorted by newest first. */
  reviews: Review[];
  /** Courses taught by the instructor. */
  courses: Course[];
}

export enum InteractionKind {
  /** Indicates that the user liked the review. */
  Like = 'like',
  /** Indicates that the user disliked the review. */
  Dislike = 'dislike',
}

export interface GetInteractionKindPayload {
  /** Interaction the user has taken for this course and referrer, if any. */
  kind?: InteractionKind;
}

export interface GetReviewsPayload {
  /** List of reviews matching the query. */
  reviews: Review[];
  /** Number of unique users who have submitted reviews (if requested). */
  uniqueUserCount?: number;
}

export interface Interaction {
  /** Kind of interaction that occurred. */
  kind: InteractionKind;
  /** ID of the user associated with the interaction. */
  userId: string;
  /** ID of the course the interaction belongs to. */
  courseId: string;
  /** Referrer source from which the interaction was made. */
  referrer: string;
}

export interface GetUserInteractionForCoursePayload {
  /** Course ID the interactions belong to. */
  course_id: string;
  /** Referrer source the interactions were recorded from. */
  referrer: string;
  /** Interactions recorded for the course and referrer. */
  interactions: Interaction[];
}

export interface Notification {
  /** Review that triggered the notification. */
  review: Review;
  /** Whether the notification has been seen. */
  seen: boolean;
  /** User ID associated with the notification. */
  userId: string;
}

export interface Subscription {
  /** Course ID the user is subscribed to. */
  courseId: string;
  /** User ID that owns the subscription. */
  userId: string;
}

export interface User {
  /** Microsoft Graph user identifier. */
  id: string;
  /** Primary email address associated with the user. */
  mail: string;
}

export interface UserResponse {
  /** Authenticated user information when available. */
  user?: User;
}

export enum Operator {
  /** All requirements must be satisfied. */
  And = 'AND',
  /** Any requirement may be satisfied. */
  Or = 'OR',
}
