[package]
name = "mcgill-courses-scraper"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
model = { path = "../../crates/model" }
rand = "0.10.0"
rayon = { workspace = true }
regex = { workspace = true }
reqwest = { version = "0.13.2", default-features = false, features = [ "blocking", "json", "rustls" ] }
scraper = "0.26.0"
serde_json = { workspace = true }
thirtyfour = "0.36.1"
tokio = { workspace = true }
totp-rs = "5.7.1"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
include_dir = { workspace = true }
mockito = { workspace = true }
pretty_assertions = { workspace = true }
