[package]
name = "server"
version = "0.0.0"
edition = "2021"
publish = false

[workspace]
members = ["crates/*", "tools/changelog-gen"]

[dependencies]
anyhow = "1.0.86"
async-mongodb-session = { version = "3.0.0", default-features = false }
async-session = "3.0.0"
axum = { version = "0.7.5", features = ["json"] }
axum-extra = { version = "0.9.3", features = ["cookie", "typed-header"] }
axum-server = "0.6.0"
base64 = "0.21.7"
bytes = "1.6.1"
chrono = "0.4.38"
clap = { version = "4.5.9", features = ["derive"] }
db = { path = "crates/db" }
dotenv = "0.15.0"
env_logger = "0.10.2"
extractor = { path = "crates/extractor" }
futures = "0.3.30"
http = "1.1.0"
log = "0.4.22"
model = { path = "crates/model" }
oauth2 = "4.4.2"
rayon = "1.10.0"
reqwest = { version = "0.11.23", default-features = false, features = [ "blocking", "json", "rustls-tls", ] }
rusoto_core = { version = "0.48.0", default-features = false, features = [ "rustls", ] }
rusoto_s3 = { version = "0.48.0", default-features = false, features = [ "rustls", ] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
sha2 = "0.10.8"
tokio = { version = "1.38.1", features = ["rt-multi-thread", "macros"] }
tower = { version = "0.4.13", features = ["tracing", "limit", "buffer"] }
tower-http = { version = "0.5.2", features = ["cors", "fs", "trace"] }
tower_governor = "0.2.0"
tracing = "0.1.40"
url = "2.5.2"
walkdir = "2.5.0"

[dev-dependencies]
hyper = { version = "1.4.1", features = ["server"] }
pretty_assertions = "1.4.0"
tempfile = "3.10.1"
tower = "0.4.13"
