[package]
name = "server"
version = "0.0.0"
edition = "2024"
publish = false

[workspace]
members = ["crates/*", "tools/changelog-generator", "tools/final-exam-schedule-parser", "tools/scraper"]

[workspace.dependencies]
anyhow = "1.0.100"
bson = { version = "3.1.0", features = ["chrono-0_4", "serde"] }
chrono = "0.4.43"
clap = { version = "4.5.56", features = ["derive"] }
dotenv = "0.15.0"
futures = "0.3.31"
include_dir = "0.7.4"
itertools = "0.14.0"
mockito = "1.7.2"
pretty_assertions = "1.4.1"
rayon = "1.11.0"
regex = "1.12.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["rt-multi-thread", "macros"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "json"] }
typeshare = "1.0.5"
utoipa = { version = "5.4.0", features = ["axum_extras"] }

[dependencies]
anyhow = { workspace = true }
async-mongodb-session = { version = "3.0.0", default-features = false, features = ["tokio-runtime"] }
async-session = "3.0.0"
axum = { version = "0.8.8", features = ["json"] }
axum-extra = { version = "0.12.5", features = ["cookie", "typed-header"] }
base64 = "0.22.1"
chrono = { workspace = true }
clap = { workspace = true }
db = { path = "crates/db" }
dotenv = { workspace = true }
futures = { workspace = true }
http = "1.4.0"
indoc = "2.0.7"
model = { path = "crates/model" }
oauth2 = "5.0.0"
reqwest = { version = "0.13.1", default-features = false, features = [ "blocking", "form", "json", "rustls"] }
rusoto_core = { version = "0.48.0", default-features = false, features = [ "rustls", ] }
rusoto_s3 = { version = "0.48.0", default-features = false, features = [ "rustls", ] }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = "0.10.9"
tokio = { workspace = true }
tower = { version = "0.5.3", features = ["buffer", "limit", "timeout", "tracing", "util"] }
tower-http = { version = "0.6.8", features = ["catch-panic", "compression-gzip", "cors", "fs", "trace"] }
tower_governor = "0.8.0"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
typeshare = { workspace = true }
url = "2.5.8"
utoipa = { workspace = true }
utoipa-scalar = { version = "0.3.0", features = ["axum"] }
uuid = { version = "1.20", features = ["v4"] }
walkdir = "2.5.0"

[dev-dependencies]
hyper = { version = "1.8.1", features = ["server"] }
mockito = { workspace = true }
pretty_assertions = { workspace = true }
tempfile = "3.24.0"
tower = { version = "0.5.3", features = ["util"] }
