[package]
name = "server"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/*"]

[dependencies]
anyhow = "1.0.69"
async-session = "3.0.0"
axum = { version = "0.6.11", features = ["headers", "json"] }
axum-server = "0.4.6"
chrono = "0.4.24"
clap = { version = "4.1.8", features = ["derive"] }
db = { path = "crates/db" }
dotenv = "0.15.0"
env_logger = "0.10.0"
extractor = { path = "crates/extractor" }
http = "0.2.9"
log = "0.4.17"
model = { path = "crates/model" }
oauth2 = "4.3.0"
rayon = "1.7.0"
reqwest = { version = "0.11.14", features = ["blocking", "json"] }
serde = { version = "1.0.156", features = ["derive"] }
serde_json = "1.0.94"
tokio = { version = "1.26.0", features = ["rt-multi-thread", "macros"] }
tower-http = { version = "0.4.0", features = ["cors"] }
