version: '3.7'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    command: --replSet rs0
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
