[package]
name = "extractor"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.69"
reqwest = { version = "0.11.14", features = ["blocking"] }
scraper = "0.15.0"
serde = { version = "1.0.156", features = ["derive"] }

[dev-dependencies]
include_dir = "0.7.3"
