[package]
name = "extractor"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.86"
model = { path = "../../crates/model" }
scraper = "0.16.0"

[dev-dependencies]
include_dir = "0.7.4"
pretty_assertions = "1.4.0"
