[package]
name = "extractor"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.98"
model = { path = "../../crates/model" }
regex = "1.11.1"
scraper = "0.23.1"

[dev-dependencies]
include_dir = "0.7.4"
pretty_assertions = "1.4.1"
