[package]
name = "final-exam-schedule-parser"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
lopdf = "0.40.0"
rayon = { workspace = true }
regex = { workspace = true }
reqwest = { version = "0.13.3", default-features = false, features = ["blocking", "rustls"] }
serde = { workspace = true }
serde_json = { workspace = true }
typeshare = { workspace = true }
