[package]
name = "db"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
bson = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
model = { path = "../model" }
mongodb = { version = "3.6.0", features = ["bson-3"] }
serde = { workspace = true }
serde_json = { workspace = true }
stop-words = "0.10.0"
thiserror = "2.0.18"
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
include_dir = { workspace = true }
pretty_assertions = { workspace = true }
regex = { workspace = true }
tempfile = { workspace = true }
