[package]
name = "model"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.69"
bson = { version = "2.6.0", features = ["chrono-0_4"] }
chrono = "0.4.24"
reqwest = { version = "0.11.14", features = ["blocking"] }
serde = { version = "1.0.156", features = ["derive"] }
