name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  all:
    name: All

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    runs-on: ${{matrix.os}}

    env:
      RUSTFLAGS: --deny warnings

    steps:
      - uses: actions/checkout@v2

      - name: Download actionlint
        id: actionlint
        run:
          bash <(curl
          https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)

      - name: Check Github Actions Workflow
        run: ${{ steps.actionlint.outputs.executable }} -color

      - name: Install Rust Toolchain Components
        uses: actions-rs/toolchain@v1
        with:
          components: clippy, rustfmt
          override: true
          toolchain: stable

      - name: Install mongodb
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew tap mongodb/brew
          brew install mongodb-community@6.0
          brew services start mongodb-community@6.0

      - uses: Swatinem/rust-cache@v1

      - name: Check Lockfile
        run: cargo update --locked --package server

      - name: Test
        if: ${{ matrix.os == 'macos-latest' }}
        run: cargo test --all

      - name: Clippy
        run: ./bin/clippy

      - name: Format
        run: cargo fmt --all -- --check

      - name: Check for Forbidden Words
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install ripgrep
          ./bin/forbid
