name: Update Changelogs

on:
  schedule:
    - cron: '0 0 * * 0' # Runs once per week
  workflow_dispatch: {}

  # TODO: Temporary, for testing, remove after confirming workflow works well
  push:
    branches:
      - automate-changelog

permissions:
  contents: write
  pull-requests: write

jobs:
  Update-Changelogs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install toolchain
        id: toolchain
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          components: llvm-tools-preview

      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32

      - name: Update changelogs
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          cargo run --manifest-path  tools/changelog-generator/Cargo.toml -- --output client/src/assets/changelog.json

      - name: Check if new changelog was added
        id: diff
        run: |
          CHANGELOG_FILE="client/src/assets/changelog.json"
          if git diff --quiet "$CHANGELOG_FILE"; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Exit if not changed
        if: steps.diff.outputs.changed == 'false'
        run: echo "Nothing changed; skipping."

      - name: Configure git
        if: steps.diff.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create branch + commit changes
        if: steps.diff.outputs.changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH="changelog-update-$(date +%s)"
          git switch -c "$BRANCH"
          git add client/src/assets/changelog.json
          git commit -m "Auto update from cronjob"
          git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" "$BRANCH"
          echo "branch=$BRANCH" >> "$GITHUB_ENV"

      - name: Open PR
        if: steps.diff.outputs.changed == 'true'
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b
        with:
          script: |
            const branch = process.env.branch;
            await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Update changelogs",
              head: branch,
              base: "master",
              body: "This PR was generated by the scheduled GitHub Action.",
              maintainer_can_modify: true
            });
